services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: todo-api-server:local
    container_name: todo-api-server
    ports:
      - '8931:8931'
    env_file:
      - path: .env
        required: false
    volumes:
      - ./data:/app/data
    restart: unless-stopped
